version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    command: ["--collector.otlp.enabled=true"]
    ports:
      - 4317:4317 # accept OpenTelemetry Protocol (OTLP) over gRPC
      - 4318:4318 # accept OpenTelemetry Protocol (OTLP) over HTTP, if enabled
      - 16686:16686 # serve frontend

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
      - 5341:80